// <auto-generated />
using System;
using ITM.Emprendimientos.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ITM.Emprendimientos.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260517025201_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ITM.Emprendimientos.Domain.Entities.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0000-0000-000000000000"),
                            CreadoEn = new DateTime(2026, 5, 17, 2, 51, 59, 245, DateTimeKind.Utc).AddTicks(3592),
                            Nombre = "Comidas y Bebidas"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0002-0000-0000-000000000000"),
                            CreadoEn = new DateTime(2026, 5, 17, 2, 51, 59, 245, DateTimeKind.Utc).AddTicks(3603),
                            Nombre = "Ropa y Accesorios"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0003-0000-0000-000000000000"),
                            CreadoEn = new DateTime(2026, 5, 17, 2, 51, 59, 245, DateTimeKind.Utc).AddTicks(3612),
                            Nombre = "Tecnología"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0004-0000-0000-000000000000"),
                            CreadoEn = new DateTime(2026, 5, 17, 2, 51, 59, 245, DateTimeKind.Utc).AddTicks(3653),
                            Nombre = "Arte y Manualidades"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0005-0000-0000-000000000000"),
                            CreadoEn = new DateTime(2026, 5, 17, 2, 51, 59, 245, DateTimeKind.Utc).AddTicks(3662),
                            Nombre = "Servicios"
                        });
                });

            modelBuilder.Entity("ITM.Emprendimientos.Domain.Entities.Horario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Dia")
                        .HasColumnType("int");

                    b.Property<Guid>("EmprendedorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly>("HoraApertura")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HoraCierre")
                        .HasColumnType("time");

                    b.Property<string>("Sede")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("EmprendedorId");

                    b.ToTable("Horarios");
                });

            modelBuilder.Entity("ITM.Emprendimientos.Domain.Entities.Producto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("AdminDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("EmprendedorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("EmprendedorId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("ITM.Emprendimientos.Domain.Entities.Ubicacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("EmprendedorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NombreSede")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReferenciaMapa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("EmprendedorId");

                    b.ToTable("Ubicaciones");
                });

            modelBuilder.Entity("ITM.Emprendimientos.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Habilitado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);

                    b.HasDiscriminator<int>("Tipo");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ITM.Emprendimientos.Domain.Entities.Administrador", b =>
                {
                    b.HasBaseType("ITM.Emprendimientos.Domain.Entities.Usuario");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.ToTable("Usuarios", t =>
                        {
                            t.Property("Descripcion")
                                .HasColumnName("Administrador_Descripcion");

                            t.Property("FotoUrl")
                                .HasColumnName("Administrador_FotoUrl");
                        });

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("ITM.Emprendimientos.Domain.Entities.Comprador", b =>
                {
                    b.HasBaseType("ITM.Emprendimientos.Domain.Entities.Usuario");

                    b.Property<string>("Apodo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SobreTi")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.ToTable("Usuarios", t =>
                        {
                            t.Property("FotoUrl")
                                .HasColumnName("Comprador_FotoUrl");
                        });

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("ITM.Emprendimientos.Domain.Entities.Emprendedor", b =>
                {
                    b.HasBaseType("ITM.Emprendimientos.Domain.Entities.Usuario");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("NombreEmprendimiento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("ITM.Emprendimientos.Domain.Entities.Horario", b =>
                {
                    b.HasOne("ITM.Emprendimientos.Domain.Entities.Emprendedor", "Emprendedor")
                        .WithMany("Horarios")
                        .HasForeignKey("EmprendedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emprendedor");
                });

            modelBuilder.Entity("ITM.Emprendimientos.Domain.Entities.Producto", b =>
                {
                    b.HasOne("ITM.Emprendimientos.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ITM.Emprendimientos.Domain.Entities.Emprendedor", "Emprendedor")
                        .WithMany("Productos")
                        .HasForeignKey("EmprendedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Emprendedor");
                });

            modelBuilder.Entity("ITM.Emprendimientos.Domain.Entities.Ubicacion", b =>
                {
                    b.HasOne("ITM.Emprendimientos.Domain.Entities.Emprendedor", "Emprendedor")
                        .WithMany("Ubicaciones")
                        .HasForeignKey("EmprendedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emprendedor");
                });

            modelBuilder.Entity("ITM.Emprendimientos.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("ITM.Emprendimientos.Domain.Entities.Emprendedor", b =>
                {
                    b.Navigation("Horarios");

                    b.Navigation("Productos");

                    b.Navigation("Ubicaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
